PRAGMA page_size=4096;
PRAGMA page_size;
PRAGMA encoding="UTF-8";
PRAGMA encoding;
PRAGMA secure_delete=1;
PRAGMA secure_delete;

CREATE TABLE 'aTabOF' (
	'id' INT UNSIGNED NOT NULL,
	'name' TEXT NOT NULL,
	'surname' TEXT NOT NULL
);

INSERT INTO aTabOF 
	(id, name, surname)
	VALUES
	(20001, 'SebastianSebastianSebastianSebastianSebastianSebastian', 'MeierMeierMeierMeier'),
	(20002, 'AdrianAlbertAlexanderAlexandraAlfredAlinaAmelieAndreAndreaAndreasAnjaAnnaAnneAnniAnnikaAntonArturAugustBenBenjaminBertaBiancaBjörnCharlotteChristianChristinaChristineChristophClaraClaudiaDanielDanielaDavidDennisDirkElfriedeEliasElisaElisabethEllaElliElsaElseEmelieEmilEmiliaEmmaEmmiEricErichErnaErnstFabianFelixFinjaFinnFlorianFrankFranzFridaFriedrichFritzGeorgGertrudGretaGustavHannaHannesHansHedwigHeinrichHelenaHeleneHenryHerbertHermannHerthaIdaIrmaIsabellIsabellaJakobJanJanaJannikJensJessicaJohannJohannaJohannesJonasJonathanJörgJosefJosephineJuliaJulianJuliusKaiKarlKarstenKatharinaKätheKatjaKatrinKerstinKurtLaraLarsLauraLeaLenaLeniLennartLeoLeonLeonieLiaLiamLillyLinaLinusLisaLottaLucaLuisLuisaLuiseLukasMajaManuelaMarcMarcoMargaretheMariaMarieMarkusMarleneMarlonMarthaMartinMartinaMathildaMatsMatteoMatthiasMaxMaximilianMeikeMelanieMelinaMiaMichaelMichaelaMikaMikeMilaMinnaMoritzNadineNeleNicoNicoleNiklasNilsNinaNoahOliverOskarOttoPaulPaulaPhilippPiaRaphaelRichardRobertRudolfSabineSandraSarahSaschaSebastianSilkeSilviaSimonSimoneSonjaSophiaSophieStefanStefanieSusanneSvenTanjaTheoThomasTillTimTimoTobiasTomTorstenVictoriaVincentWalterWernerWilhelmWilliYvonneZoeAlbrechtArnoldBauerBaumannBeckBeckerBergerBergmannBöhmBrandtBraunBuschDietrichEngelFischerFrankFrankeFriedrichFuchsGrafGroßGüntherHaasHahnHartmannHeinrichHerrmannHoffmannHofmannHornHuberJägerJungKaiserKellerKleinKochKöhlerKönigKrämerKrausKrauseKrügerKuhnKühnLangLangeLehmannLorenzLudwigMaierMartinMayerMeierMeyerMöllerMüllerNeumannOttoPetersPfeifferPohlRichterRothSauerSchäferSchmidSchmidtSchmittSchmitzSchneiderScholzSchreiberSchröderSchubertSchulteSchulzSchulzeSchumacherSchusterSchwarzSeidelSimonSommerSteinThomasVogelVogtVoigtWagnerWalterWeberWeißWernerWinklerWinterWolfWolffZieglerZimmermannAdrianAlbertAlexanderAlexandraAlfredAlinaAmelieAndreAndreaAndreasAnjaAnnaAnneAnniAnnikaAntonArturAugustBenBenjaminBertaBiancaBjörnCharlotteChristianChristinaChristineChristophClaraClaudiaDanielDanielaDavidDennisDirkElfriedeEliasElisaElisabethEllaElliElsaElseEmelieEmilEmiliaEmmaEmmiEricErichErnaErnstFabianFelixFinjaFinnFlorianFrankFranzFridaFriedrichFritzGeorgGertrudGretaGustavHannaHannesHansHedwigHeinrichHelenaHeleneHenryHerbertHermannHerthaIdaIrmaIsabellIsabellaJakobJanJanaJannikJensJessicaJohannJohannaJohannesJonasJonathanJörgJosefJosephineJuliaJulianJuliusKaiKarlKarstenKatharinaKätheKatjaKatrinKerstinKurtLaraLarsLauraLeaLenaLeniLennartLeoLeonLeonieLiaLiamLillyLinaLinusLisaLottaLucaLuisLuisaLuiseLukasMajaManuelaMarcMarcoMargaretheMariaMarieMarkusMarleneMarlonMarthaMartinMartinaMathildaMatsMatteoMatthiasMaxMaximilianMeikeMelanieMelinaMiaMichaelMichaelaMikaMikeMilaMinnaMoritzNadineNeleNicoNicoleNiklasNilsNinaNoahOliverOskarOttoPaulPaulaPhilippPiaRaphaelRichardRobertRudolfSabineSandraSarahSaschaSebastianSilkeSilviaSimonSimoneSonjaSophiaSophieStefanStefanieSusanneSvenTanjaTheoThomasTillTimTimoTobiasTomTorstenVictoriaVincentWalterWernerWilhelmWilliYvonneZoeAlbrechtArnoldBauerBaumannBeckBeckerBergerBergmannBöhmBrandtBraunBuschDietrichEngelFischerFrankFrankeFriedrichFuchsGrafGroßGüntherHaasHahnHartmannHeinrichHerrmannHoffmannHofmannHornHuberJägerJungKaiserKellerKleinKochKöhlerKönigKrämerKrausKrauseKrügerKuhnKühnLangLangeLehmannLorenzLudwigMaierMartinMayerMeierMeyerMöllerMüllerNeumannOttoPetersPfeifferPohlRichterRothSauerSchäferSchmidSchmidtSchmittSchmitzSchneiderScholzSchreiberSchröderSchubertSchulteSchulzSchulzeSchumacherSchusterSchwarzSeidelSimonSommerSteinThomasVogelVogtVoigtWagnerWalterWeberWeißWernerWinklerWinterWolfWolffZieglerZimmermannAdrianAlbertAlexanderAlexandraAlfredAlinaAmelieAndreAndreaAndreasAnjaAnnaAnneAnniAnnikaAntonArturAugustBenBenjaminBertaBiancaBjörnCharlotteChristianChristinaChristineChristophClaraClaudiaDanielDanielaDavidDennisDirkElfriedeEliasElisaElisabethEllaElliElsaElseEmelieEmilEmiliaEmmaEmmiEricErichErnaErnstFabianFelixFinjaFinnFlorianFrankFranzFridaFriedrichFritzGeorgGertrudGretaGustavHannaHannesHansHedwigHeinrichHelenaHeleneHenryHerbertHermannHerthaIdaIrmaIsabellIsabellaJakobJanJanaJannik', 'Huber'),
	(20003, 'Marlene', 'Kuhn'),
	(20004, 'Victoria', 'Winter'),
	(20005, 'Walter', 'Kaiser');

PRAGMA secure_delete=0;
PRAGMA secure_delete;

DELETE FROM aTabOF where id == 20001;
